/**
 * @license
 * Copyright 2014 The Lovefield Project Authors. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
goog.provide('lf.testing.hrSchema.samples');


/**
 * @type {!Array<string>}
 * @const
 */
lf.testing.hrSchema.samples.FIRST_NAMES = [
  'Aaliyah',
  'Aaron',
  'Abigail',
  'Adam',
  'Addison',
  'Adrian',
  'Aiden',
  'Alex',
  'Alexa',
  'Alexander',
  'Alexandra',
  'Alexis',
  'Alice',
  'Allison',
  'Alyssa',
  'Amelia',
  'Andrew',
  'Anna',
  'Annabelle',
  'Anthony',
  'Aria',
  'Arianna',
  'Asher',
  'Aubrey',
  'Audrey',
  'Austin',
  'Ava',
  'Avery',
  'Bailey',
  'Bella',
  'Benjamin',
  'Bentley',
  'Blake',
  'Brandon',
  'Brayden',
  'Brianna',
  'Brody',
  'Brooke',
  'Brooklyn',
  'Caleb',
  'Cameron',
  'Caroline',
  'Carson',
  'Carter',
  'Charlie',
  'Charlotte',
  'Chase',
  'Chloe',
  'Christian',
  'Christopher',
  'Claire',
  'Clara',
  'Cole',
  'Colin',
  'Colton',
  'Connor',
  'Cooper',
  'Daniel',
  'David',
  'Declan',
  'Dominic',
  'Dylan',
  'Easton',
  'Eleanor',
  'Elena',
  'Eli',
  'Eliana',
  'Elijah',
  'Elise',
  'Elizabeth',
  'Ella',
  'Ellie',
  'Emily',
  'Emma',
  'Ethan',
  'Eva',
  'Evan',
  'Evelyn',
  'Gabriel',
  'Gabriella',
  'Gavin',
  'Gianna',
  'Grace',
  'Grayson',
  'Hailey',
  'Hannah',
  'Harper',
  'Harrison',
  'Hayden',
  'Henry',
  'Hudson',
  'Hunter',
  'Ian',
  'Isaac',
  'Isabella',
  'Isabelle',
  'Isaiah',
  'Isla',
  'Jace',
  'Jack',
  'Jackson',
  'Jacob',
  'Jake',
  'James',
  'Jasmine',
  'Jason',
  'Jayden',
  'Jeremiah',
  'John',
  'Jonathan',
  'Jordan',
  'Joseph',
  'Joshua',
  'Julia',
  'Julian',
  'Kaitlyn',
  'Kate',
  'Kayla',
  'Kaylee',
  'Kendall',
  'Kennedy',
  'Kylie',
  'Landon',
  'Lauren',
  'Layla',
  'Leah',
  'Leo',
  'Levi',
  'Liam',
  'Lillian',
  'Lily',
  'Lincoln',
  'Logan',
  'Lucas',
  'Lucy',
  'Luke',
  'Lyla',
  'Mackenzie',
  'Madelyn',
  'Madison',
  'Makayla',
  'Maria',
  'Mason',
  'Matthew',
  'Max',
  'Maya',
  'Mia',
  'Micah',
  'Michael',
  'Mila',
  'Miles',
  'Molly',
  'Morgan',
  'Natalie',
  'Nathan',
  'Nathaniel',
  'Nevaeh',
  'Nicholas',
  'Noah',
  'Nolan',
  'Nora',
  'Oliver',
  'Olivia',
  'Owen',
  'Paige',
  'Parker',
  'Peyton',
  'Piper',
  'Quinn',
  'Reagan',
  'Reese',
  'Riley',
  'Riley',
  'Ruby',
  'Ryan',
  'Ryder',
  'Sadie',
  'Samantha',
  'Samuel',
  'Sarah',
  'Savannah',
  'Scarlett',
  'Sean',
  'Sebastian',
  'Sienna',
  'Sophia',
  'Sophie',
  'Stella',
  'Sydney',
  'Taylor',
  'Thomas',
  'Tristan',
  'Tyler',
  'Victoria',
  'Violet',
  'William',
  'Wyatt',
  'Xavier',
  'Zachary',
  'Zoe'
];


/**
 * @type {!Array<string>}
 * @const
 */
lf.testing.hrSchema.samples.LAST_NAMES = [
  'Adams',
  'Alexander',
  'Allen',
  'Anderson',
  'Bailey',
  'Baker',
  'Barnes',
  'Bell',
  'Bennett',
  'Brooks',
  'Brown,',
  'Bryant',
  'Butler',
  'Campbell',
  'Carter',
  'Clark',
  'Coleman',
  'Collins',
  'Cook',
  'Cooper',
  'Cox',
  'Davis,',
  'Diaz',
  'Edwards',
  'Evans',
  'Flores',
  'Foster',
  'Garcia',
  'Gonzales',
  'Gonzalez',
  'Gray',
  'Green',
  'Griffin',
  'Hall',
  'Harris',
  'Hayes',
  'Henderson',
  'Hernandez',
  'Hill',
  'Howard',
  'Hughes',
  'Jackson',
  'James',
  'Jenkins',
  'Johnson',
  'Jones,',
  'Kelly',
  'King',
  'Lee',
  'Lewis',
  'Long',
  'Lopez',
  'Martin',
  'Martinez',
  'Miller,',
  'Mitchell',
  'Moore',
  'Morgan',
  'Morris',
  'Murphy',
  'Nelson',
  'Parker',
  'Patterson',
  'Perez',
  'Perry',
  'Peterson',
  'Phillips',
  'Powell',
  'Price',
  'Ramirez',
  'Reed',
  'Richardson',
  'Rivera',
  'Roberts',
  'Robinson',
  'Rodriguez',
  'Rogers',
  'Ross',
  'Russell',
  'Sanchez',
  'Sanders',
  'Scott',
  'Simmons',
  'Smith',
  'Stewart',
  'Taylor',
  'Thomas',
  'Thompson',
  'Torres',
  'Turner',
  'Walker',
  'Ward',
  'Washington',
  'Watson',
  'White',
  'Williams',
  'Wilson',
  'Wood',
  'Wright',
  'Young'
];


/**
 * @type {!Array<string>}
 * @const
 */
lf.testing.hrSchema.samples.JOB_TITLES = [
  'Accountant, Private',
  'Accountant, Public',
  'Accounting Specialist',
  'Actuary',
  'Administrative Services Manager',
  'Administrator Payroll',
  'Advertising and Promotions Manager',
  'Advertising Sales Agent',
  'Agent and Business Manager of Artists, Performers and Athletes',
  'Aircraft Mechanic',
  'Aircraft Technician',
  'Antenna Engineer',
  'Antenna Operator',
  'Appraiser and Assessor of Real Estate',
  'Arbitrators, Mediators, and Conciliators',
  'Auditor',
  'Brand Manager',
  'Budget Analyst',
  'Business Analyst',
  'Business Continuity Planner',
  'Business Intelligence Analyst',
  'Chief Executive Officer',
  'Chief Financial Officer',
  'Chief Information Officer',
  'Community Service Manager',
  'Compensation or Benefits Manager',
  'Computer and Information Systems Manager',
  'Credit Analyst',
  'Criminal Investigator and Special Agent',
  'Customer Service Representative',
  'Customs Broker',
  'Design Engineer',
  'Document Management Specialist',
  'Economist',
  'Electrical Engineer',
  'Employment Interviewer',
  'Employment Manager',
  'Energy Broker',
  'Engineer',
  'Engineering Technician',
  'Engine Mechanic',
  'Event Planner',
  'Financial Analyst',
  'Financial Examiner',
  'Financial Manager',
  'Financial Planner',
  'First-Line Supervisors and Manager/Supervisor',
  'Food Service Manager',
  'Fraud Examiner',
  'Gaming manager',
  'Grant writer',
  'Human Resources Assistant',
  'Human Resources Coordinator',
  'Human Resources Generalist',
  'Human Resources Specialist',
  'Immigration and Customs Inspector',
  'Insurance Underwriter',
  'Java Developer',
  'Job Analysis Specialist',
  'Labor Relations Specialist',
  'Loan Officer',
  'Lodging Manager',
  'Loss Prevention Specialist',
  'Management Analyst',
  'Manufacturing Engineer',
  'Marketing Manager',
  'Market Researcher',
  'Mechanical Engineer',
  'Meeting and Convention Planner',
  'Network Engineer',
  'Nurse',
  'Occupational Therapist',
  'Payroll Clerk',
  'Payroll Specialist',
  'Personal Financial Advisor/Planner',
  'Personnel Recruiter',
  'Pharmacist',
  'Physical Therapist',
  'Process Engineer',
  'Project Engineer',
  'Project Manager',
  'Property, Real Estate, and Community Association Manager',
  'Public Relations Specialist',
  'Purchasing manager, Buyer, and Purchasing agent',
  'Quality Engineer',
  'Quantum Physicist',
  'Real estate broker and sales agent',
  'Recruiter',
  'Registered Nurse',
  'Senior Software Engineer',
  'Software Engineer',
  'Speech Language Pathologist',
  'Speech Pathologist Assistant',
  'Systems Administrator',
  'Systems Engineer',
  'Tax Examiner, Collector, and Revenue Agent',
  'Technical Recruiter',
  'Technician',
  'Trainer',
  'Training and Development Manager',
  'Training Specialist',
  'Web Developer'
];


/**
 * @type {!Array<string>}
 * @const
 */
lf.testing.hrSchema.samples.DEPARTMENT_NAMES = [
  'Marketing',
  'Human Resources',
  'Financial',
  'Purchasing',
  'Sales',
  'IT',
  'Inventory',
  'Quality Asurance',
  'Insurance',
  'Licenses',
  'Operational',
  'Staff',
  'Customer Service',
  'Organizational'
];
